name: pythia-dev
channels:
  - defaults
dependencies:
  - fiona=1.8.4
  - jinja2=2.10.1
  - numpy=1.16.5
  - pandas=0.25.1
  - pillow=5.4.1
  - rasterio=1.0.21
  - rtree=0.8.3
  - shapely=1.6.4
  - pytest=5.1.2
