[tool.poetry]
name = "pythia"
version = "2.3.0"
description = "An extensible gridded modeling framework for point-based modeling."
authors = ["Christopher Villalobos <cvillalobos@ufl.edu>"]
license = "BSD-3-Clause"

[tool.poetry.dependencies]
python = ">=3.8,<4.0"

numpy = [
  {version = "^1.16", python = "<3.12"},
  {version = "^2.4",  python = ">=3.12"}
]

Fiona = [
  {version = "^1.9",  python = "<3.12"},
  {version = "^1.10", python = ">=3.12"}
]

rasterio = [
  {version = "^1.0",  python = "<3.12"},
  {version = "^1.5",  python = ">=3.12"}
]

jinja2 = "^3.0"
rtree  = "^0.8"

[tool.poetry.group.dev.dependencies]
pytest = ">=7.4,<9"
flake8 = "^3.9.2"
neovim = "^0.3.1"
python-lsp-server = {extras = ["all"], version = "^1.2.4"}
pyls-isort = "^0.2.2"
python-lsp-black = "^1.0.0"
pylsp-rope = "^0.1.7"
pyls-flake8 = "^0.4.0"
ipython = "^8.1.0"
black = "^22.8.0"

[tool.poetry.scripts]
pythia = "pythia.cli:main"

[build-system]
requires = ["setuptools", "poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
